name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Add GitHub Packages source if it does not exist
        run: |
          if ! dotnet nuget list source | grep -q "${{ vars.NUGET_SOURCE }}"; then
            dotnet nuget add source ${{ vars.NUGET_SOURCE }} --name github --username ${{ github.actor }} --password ${{ secrets.NUGET_SOURCE_SECRET }} --store-password-in-clear-text
          else
            echo "Source already exists, skipping addition."
      
      - name: Restore dependencies
        run: dotnet restore "src/EventStorage.csproj"

      - name: Build the EventStorage in Debug mode
        if: github.event_name == 'pull_request'
        run: dotnet build "src/EventStorage.csproj" --configuration Debug --no-restore

      - name: Build the EventStorage in Release mode
        if: github.event_name != 'pull_request'
        run: dotnet build "src/EventStorage.csproj" --configuration Release --no-restore