name: Build abd publish NuGet package

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      version:
        required: true
        type: string
      project_file_path:
        required: true
        type: string

jobs:
  BuildAndPushPackage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project_file_path }}

      - name: Build the project
        run: dotnet build ${{ inputs.project_file_path }} --configuration Release --no-restore

      - name: Pack the NuGet package
        run: dotnet pack ${{ inputs.project_file_path }} --configuration Release --output ./nupkgs -p:PackageId="${{ inputs.package_name }}" -p:Version="${{ inputs.version }}"

      - name: Push the package to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/alifcapital/index.json" --api-key ${{ secrets.EVENT_STORAGE_SECRET }}