name: Build abd publish NuGet package

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      version:
        required: true
        type: string
      project_file_path:
        required: true
        type: string

jobs:
  BuildAndPushPackage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project_file_path }}

      - name: Build the project
        run: dotnet build ${{ inputs.project_file_path }} --configuration Release --no-restore

      - name: Add NuGet source if it doesn't exist
        run: |
          if ! dotnet nuget list source | grep -q "github"; then
            dotnet nuget add source "https://nuget.pkg.github.com/alifcapital/index.json" \
              --name github \
              --username alifcapital \
              --password ${{ secrets.GITHUB_PAT }} \
              --store-password-in-clear-text
          fi

      - name: Pack the NuGet package
        run: dotnet pack ${{ inputs.project_file_path }} --configuration Release --no-build --output .

      - name: Push the package to GitHub Packages
        run: dotnet nuget push *.nupkg --source "https://nuget.pkg.github.com/alifcapital/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}