name: Release Event storage

on:
  push:
    branches: [ "main" ]
    paths:
      - EventStorage/**
      - .github/workflows/release-event-storage.yml
      - .github/workflows/service-versioning.yml
      - .github/workflows/build-and-push-nuget-package.yml

permissions:
  contents: write  # Grant the workflow permission to push to the repository

jobs:
  Versioning:
    uses: ./.github/workflows/service-versioning.yml
    with:
      project_file_path: "src/EventStorage.csproj"
      should_add_version_tag: ${{ github.ref == 'refs/heads/main' }}
  
  Release:
    needs: Versioning
    uses: ./.github/workflows/build-and-push-nuget-package.yml
    with:
      project_file_path: 'src/EventStorage.csproj'
      package_name: ${{ vars.PACKAGENAME }}
      version: ${{ needs.Versioning.outputs.version }}
    secrets: inherit
